# Generated by Django 6.0.3 on 2026-04-01 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النموذج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('min_vram', models.IntegerField(verbose_name='الحد الأدنى للذاكرة الفيديو (GB)')),
                ('rec_vram', models.IntegerField(verbose_name='الذاكرة الفيديو الموصى بها (GB)')),
                ('min_ram', models.IntegerField(verbose_name='الحد الأدنى للذاكرة (GB)')),
                ('inference_speed_slow', models.CharField(max_length=50, verbose_name='سرعة الاستدلاء البطيئة')),
                ('inference_speed_fast', models.CharField(max_length=50, verbose_name='سرعة الاستدلاء السريعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نموذج ذكاء اصطناعي',
                'verbose_name_plural': 'نماذج الذكاء الاصطناعي',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكون')),
                ('brand', models.CharField(max_length=100, verbose_name='الشركة')),
                ('component_type', models.CharField(choices=[('cpu', 'معالج'), ('gpu', 'كرت شاشة'), ('ram', 'ذاكرة'), ('ssd', 'تخزين'), ('motherboard', 'لوحة أم')], max_length=20, verbose_name='نوع المكون')),
                ('specs', models.JSONField(verbose_name='المواصفات التفصيلية')),
                ('performance_score', models.IntegerField(default=0, verbose_name='درجة الأداء')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('affiliate_link', models.URLField(blank=True, verbose_name='رابط الشراء')),
                ('image', models.ImageField(upload_to='components/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مكون',
                'verbose_name_plural': 'المكونات',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجهاز')),
                ('brand', models.CharField(max_length=100, verbose_name='الشركة المصنعة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('device_type', models.CharField(choices=[('laptop', 'لابتوب'), ('handheld', 'جهاز يد'), ('desktop', 'كمبيوتر مكتبي')], max_length=20, verbose_name='نوع الجهاز')),
                ('processor', models.CharField(max_length=200, verbose_name='المعالج')),
                ('ram', models.CharField(max_length=50, verbose_name='الذاكرة العشوائية')),
                ('storage', models.CharField(max_length=100, verbose_name='التخزين')),
                ('gpu', models.CharField(max_length=200, verbose_name='كرت الشاشة')),
                ('display', models.CharField(max_length=200, verbose_name='الشاشة')),
                ('battery', models.CharField(max_length=100, verbose_name='البطارية')),
                ('benchmark_score', models.IntegerField(default=0, verbose_name='درجة الأداء')),
                ('gaming_score', models.IntegerField(default=0, verbose_name='درجة الألعاب')),
                ('ai_score', models.IntegerField(default=0, verbose_name='درجة الذكاء الاصطناعي')),
                ('dev_score', models.IntegerField(default=0, verbose_name='درجة التطوير')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('affiliate_link', models.URLField(blank=True, verbose_name='رابط الشراء')),
                ('image', models.ImageField(upload_to='devices/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
                'ordering': ['-benchmark_score'],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأداة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('category', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='التقييم')),
                ('downloads', models.IntegerField(default=0, verbose_name='عدد التحميلات')),
                ('marketplace_link', models.URLField(verbose_name='رابط المتجر')),
                ('features', models.JSONField(verbose_name='المميزات')),
                ('image', models.ImageField(blank=True, upload_to='extensions/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إضافة',
                'verbose_name_plural': 'الإضافات',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم اللعبة')),
                ('genre', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('min_processor', models.CharField(max_length=200, verbose_name='المعالج الأدنى')),
                ('min_ram', models.CharField(max_length=50, verbose_name='الذاكرة الأدنى')),
                ('min_gpu', models.CharField(max_length=200, verbose_name='كرت الشاشة الأدنى')),
                ('rec_processor', models.CharField(max_length=200, verbose_name='المعالج الموصى به')),
                ('rec_ram', models.CharField(max_length=50, verbose_name='الذاكرة الموصى بها')),
                ('rec_gpu', models.CharField(max_length=200, verbose_name='كرت الشاشة الموصى به')),
                ('expected_fps_low', models.IntegerField(default=30, verbose_name='أقل FPS')),
                ('expected_fps_high', models.IntegerField(default=60, verbose_name='أعلى FPS')),
                ('image', models.ImageField(upload_to='games/', verbose_name='صورة اللعبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'لعبة',
                'verbose_name_plural': 'الألعاب',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('summary', models.TextField(verbose_name='الملخص')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('review_type', models.CharField(choices=[('device', 'جهاز'), ('component', 'مكون'), ('extension', 'إضافة'), ('comparison', 'مقارنة')], max_length=20, verbose_name='نوع المراجعة')),
                ('featured_image', models.ImageField(upload_to='reviews/', verbose_name='الصورة المميزة')),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='التقييم العام')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.component', verbose_name='المكون')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.device', verbose_name='الجهاز')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.extension', verbose_name='الإضافة')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
